apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
        - name: sample-service
          image: REPLACE_WITH_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "base"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
